In [ ]:
import numpy as np

In [ ]:
arr= np.array([1,2,3,4,5,67,78,90,6])
print("basic slicing",arr[2:7])
print("with step",arr[1:8:2])
print("negative indexing",arr[-3])
arr_2d= np.arange(6).reshape(2,3)
print(arr_2d)
print("specific element",arr_2d[1,1])
print("specific element",arr_2d[1])
print("specific element",arr_2d[:,1])
unsorted = np.array([3,4,5,2,7,1,8,6,9,10])
print("sorted array",np.sort(unsorted))
arr_2d_unsorted= np.array([[3,4,5],[2,7,1],[8,6,9]])
print("sorted array",np.sort(arr_2d_unsorted,axis=0))

basic slicing [ 3  4  5 67 78]
with step [ 2  4 67 90]
negative indexing 78
[[0 1 2]
 [3 4 5]]
specific element 4
specific element [3 4 5]
specific element [1 4]
sorted array [ 1  2  3  4  5  6  7  8  9 10]
sorted array [[2 4 1]
 [3 6 5]
 [8 7 9]]


In [ ]:
# filter
n=np.arange(11)
even_number= n[n%2==0]
print(even_number)
#  with mask
mask= (n>2) & (n<9)
print(n[mask])
# fancy indxing vs np.where()
indices= [1,4,6]
print(  n[indices])
r= np.where(n>5)
print(r)
print(n[r])

[ 0  2  4  6  8 10]
[3 4 5 6 7 8]
[1 4 6]
(array([ 6,  7,  8,  9, 10]),)
[ 6  7  8  9 10]


In [ ]:
condition_array= np.where(n>5,n*4,n*2)
print(condition_array)

[ 0  2  4  6  8 10 24 28 32 36 40]


In [ ]:
# adding and removing data
arr1= np.array([1,2,3])
arr2= np.array([4,5,6])
c=arr1+arr2
print(c)
com=np.concatenate((arr1,arr2))
print(com)

[5 7 9]
[1 2 3 4 5 6]


In [ ]:
# array compatibility
a=np.array([1,2,3])
b=np.array([4,5,6,7])
c=np.array([1,2,3,8,9,6,4])

print("compatibility ",a.shape==b.shape==c.shape)

compatibility  False


In [ ]:
original=np.array([[1,2],[3,4]])
new=np.array([5,6])
print(original+new)
with_new=np.vstack((original,new))
print(with_new)
with_col=np.hstack((original,new.reshape(2,1)))
print(with_col)
arr=np.array([1,2,3,4,5,6])
dele = np.delete(arr,2)
print(dele)#array after deleting that element from array

[[ 6  8]
 [ 8 10]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
[1 2 4 5 6]
