In [ ]:
##numpy array and basics
# learn about numpy with myself

In [ ]:
import numpy as np

In [ ]:
# creating array from list
arr_1d = np.array([1,2,3,4,5,6])
print ("1d array : ",arr_1d)
arr_2d = np.array([[1,2,3],[4,5,6]])
print ("2d array : ",arr_2d)
arr_3d = np.array([[[1,2,3],[4,5,6],[3,4,5]]])
print ("3d array : ",arr_3d)

1d array :  [1 2 3 4 5 6]
2d array :  [[1 2 3]
 [4 5 6]]
3d array :  [[[1 2 3]
  [4 5 6]
  [3 4 5]]]


In [ ]:
# list vs array
py_list = [1,2,3]
print("multiplication of list :",py_list*2)

nd_arr = np.array([1,2,3]) #element wise multiplication
print("multiplication of array :",nd_arr*2)

multiplication of list : [1, 2, 3, 1, 2, 3]
multiplication of array : [2 4 6]


In [ ]:
z = np.zeros((4,3))
print("arr :",z)
o = np.ones((4,3))
print("arr :",o)
f = np.full((4,3),9)
print("arr :",f)
r = np.random.random((4,3))*9
print("arr :",r)

arr : [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
arr : [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr : [[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]]
arr : [[5.82322626 4.13094995 6.22164279]
 [1.93015914 5.52666357 5.55603186]
 [7.20202396 3.79597351 1.10069293]
 [5.26946704 5.96444574 0.25789466]]


In [ ]:
# /array prop
arr=np.array([[1,23,3],[3,4,5]])
print("shape :", arr.shape)
print("dimn :", arr.ndim)
print("size:", arr.size)
print("d type:", arr.dtype)

shape : (2, 3)
dimn : 2
size: 6
d type: int64


In [ ]:
# array reshape
a= np.arange(12)
print("original array" , a)

original array [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# array reshape
a= np.arange(12).reshape(4,3)
print("original array" , a)
r=a.flatten()
print (r)#ravel (return view ,instead of copy)
# transpose
t= a.T
print(t)


original array [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [ ]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b
c = a - b
c
b**2
np.sin(a)
# a < 35

array([ 0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [ ]:
a= np.arange(15).reshape(3,5)
a
a.shape
a.ndim
a.dtype.name
a.itemsize
a.size
type(a)
c=np.array([[1,2],[3,4]],dtype=complex)
c
np.zeros((3,4))
np.ones((2,3,4),dtype=np.int16)
np.empty((2,3))
np.arange(10,30,5)
np.arange(0,2,0.3)
from numpy import pi
np.linspace(0,2,9)
x=np.linspace(0,2*pi,100)
f=np.sin(x)

In [ ]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
A * B     # elementwise product
A @ B     # matrix product
A.dot(B)  # another matrix product

array([[5, 4],
       [3, 4]])

In [ ]:
rg = np.random.default_rng(1)  # create instance of default random number generator
rg
a = np.ones((2, 3), dtype=int)
a
b = rg.random((2, 3))
b
a *= 3
a
b += a
b
# a += b  # b is not automatically converted to integer type


array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [ ]:
a = rg.random((2, 3))
a
a.sum(axis= 0 )
a.min(axis=1)
a.cumsum(axis=1)
B = np.arange(3)
B
np.exp(B)
np.sqrt(B)
C = np.array([2., -1., 4.])
C
np.add(B, C)

array([2., 0., 6.])